[package]
name = "libbpf-sys"
version = "0.0.6-1"
description = "Rust bindings to libbpf from the Linux kernel"
readme = "README.md"
repository = "https://github.com/alexforster/libbpf-sys"
homepage = "https://github.com/alexforster/libbpf-sys"
keywords = ["bpf", "ebpf", "xdp"]
authors = ["Alex Forster <alex@alexforster.com>"]
license = "BSD-2-Clause"
edition = "2018"
build = "build.rs"
links = "bpf"

[badges]
travis-ci = { repository = "alexforster/libbpf-sys" }
maintenance = { status = "passively-maintained" }

[build-dependencies]
bindgen = "0.51"

[lib]
crate-type = ["lib", "staticlib"]
